### PR TITLE
Problem with rendering

### PR DESCRIPTION
**Pull request by MayMeow**
After i pulled changes from your repository i got this error

image

To make it work i changed head.html partial to check if that `microblog_head.html` partial exists

### CODE REVIEW

**Comment by MattSLangford** [comment]
Hmm. `microblog_head.html` is provided directly from micro.blog, not the Tiny Theme. It includes some critical stuff like enabling custom css amongst other things. I'm guessing M.b was having an issue on their end at the time.

**Comment by MayMeow** [comment]
yes, I noticed that after changing the code my custom colors stopped working. so I put this pull to draft. and eventually, I could close it after I'll have more information.

**Comment by manton** [comment]
I figured out why this was happening. There was a bug if you had never installed a new theme from the plug-in directory. I'm fixing it now… As a work-around in the meantime, it should go away if you go to Plug-ins → Find Plug-ins and install any theme.

**Comment by manton** [comment]
Should be fixed now! Thanks.

**Pull request closed without merging**
